// Build extension/src/catalog.js from Room TBA's local AMIS class caches.
// Usage: node scratch/build_catalog.mjs ~/dev/uplbtools/room-tba/data
//
// Reads every amis-*.json (shape { term_id, classes: [...] }), keeps only the
// course catalog fields (code, title, units, sem_offered, requisites) for
// courses that some curriculum.js program lists or a specialization names, and counts in how many
// observed 1st sem / 2nd sem / midyear terms each course had an active
// section. No faculty, room or enrollment data is written.
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const { UPLB_PROGRAMS } = require(join(root, 'extension/src/curriculum.js'));
const { combineRequisites, extractCode, normCode } = require(join(root, 'extension/src/scheduler.js'));

const dataDir = process.argv[2];
if (!dataDir) {
  console.error('usage: node scratch/build_catalog.mjs <dir with amis-*.json>');
  process.exit(1);
}

const wanted = new Set();
Object.values(UPLB_PROGRAMS).forEach(p => (p.majorCourses || []).forEach(c => {
  const code = extractCode(c.code);
  if (code) wanted.add(code);
}));
// Specialization pools list courses that are not checklist rows.
Object.values(UPLB_PROGRAMS).forEach(p => Object.values(p.specializations || {})
  .forEach(s => s.pools.forEach(pool => pool.courses.forEach(code => wanted.add(code)))));

const files = readdirSync(dataDir).filter(f => /^amis-.*\.json$/.test(f));
const terms = [];
for (const f of files) {
  const d = JSON.parse(readFileSync(join(dataDir, f), 'utf8'));
  terms.push({ termId: Number(d.term_id), classes: d.classes || [] });
}
// Same term cached twice under different names counts once.
const byTerm = new Map();
terms.forEach(t => byTerm.set(t.termId, t));
const sorted = Array.from(byTerm.values()).sort((a, b) => a.termId - b.termId);

const catalog = {};
const seenTerms = { 1: 0, 2: 0, 3: 0 };
for (const { termId, classes } of sorted) {
  const sem = termId % 10;
  seenTerms[sem]++;
  const activeHere = new Set();
  for (const cls of classes) {
    const course = cls.course;
    if (!course) continue;
    const code = normCode(course.course_code);
    if (!wanted.has(code)) continue;
    if (cls.status === 'Active' && cls.max_class_size > 0) activeHere.add(code);
    // Later terms overwrite earlier ones, so the newest catalog text wins.
    const req = combineRequisites(course.requisites || []);
    const entry = catalog[code] || { offered: { 1: 0, 2: 0, 3: 0 } };
    entry.units = Number.parseFloat(course.units) || entry.units || 0;
    entry.title = course.title || entry.title;
    entry.catalogSem = course.sem_offered && course.sem_offered !== '--' ? course.sem_offered.replace(/"/g, '') : entry.catalogSem;
    entry.pre = req.pre;
    entry.co = req.co;
    entry.standing = req.standing;
    entry.coi = req.coi;
    entry.note = req.note;
    catalog[code] = entry;
  }
  activeHere.forEach(code => { catalog[code].offered[sem]++; });
}

// Drop empty fields to keep the file small.
const compact = {};
Object.keys(catalog).sort().forEach(code => {
  const e = catalog[code];
  const out = { units: e.units, title: e.title, offered: e.offered };
  if (e.catalogSem) out.catalogSem = e.catalogSem;
  if (e.pre.length) out.pre = e.pre;
  if (e.co.length) out.co = e.co;
  if (e.standing) out.standing = e.standing;
  if (e.coi) out.coi = true;
  if (e.note) out.note = e.note;
  compact[code] = out;
});

const header = `// Generated by scratch/build_catalog.mjs from AMIS class listings
// (terms ${sorted.map(t => t.termId).join(', ')}). Do not edit by hand.
// offered = number of observed terms with an active section, out of
// ${seenTerms[1]} first sems, ${seenTerms[2]} second sems and ${seenTerms[3]} midyears.
// pre = AND of OR-groups. co = corequisites (may share a term).
`;
const body = `const UPLB_CATALOG = ${JSON.stringify(compact)};
if (typeof module !== 'undefined') module.exports = { UPLB_CATALOG };
`;
const outPath = join(root, 'extension/src/catalog.js');
writeFileSync(outPath, header + body);
const size = Buffer.byteLength(header + body);
console.log(`catalog.js: ${Object.keys(compact).length} of ${wanted.size} curriculum courses, ${(size / 1024).toFixed(1)} KB`);
const missing = Array.from(wanted).filter(c => !compact[c]);
console.log(`not in AMIS data (${missing.length}): ${missing.slice(0, 60).join(', ')}${missing.length > 60 ? ' ...' : ''}`);
